services:
  - name: my-django-backend
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn amazonCloneBackend.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
